### ISSUE TITLE
Thread's interrupt flag was somehow cleared throwing an AssertionError 

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Core#175]
error reported when shutting down a component that tails a number of queues:

```
java.lang.AssertionError
at net.openhft.chronicle.core.Jvm$CommonInterruptible.interrupt(Jvm.java:1044)
at net.openhft.chronicle.core.Jvm.lambda$doNotCloseOnInterrupt9$4(Jvm.java:935)
at jdk.proxy1/com.sun.proxy.jdk.proxy1.$Proxy29.interrupt(Unknown Source)
at java.base/java.lang.Thread.interrupt(Thread.java:996)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.interruptIfStarted(ThreadPoolExecutor.java:665)
at java.base/java.util.concurrent.ThreadPoolExecutor.interruptWorkers(ThreadPoolExecutor.java:763)
at java.base/java.util.concurrent.ThreadPoolExecutor.shutdownNow(ThreadPoolExecutor.java:1409)
at java.base/java.util.concurrent.Executors$DelegatedExecutorService.shutdownNow(Executors.java:693)
```

Looking at the code in CommonInterruptible, it seems as though the Thread's interrupt flag was somehow cleared before the assert check was made:

```
assert Thread.currentThread().isInterrupted();
```

Since this has been observed, please log a warning rather than throwing an AssertionError when the thread's interrupted flag has been cleared.

The environment was JDK15, running inside docker on ubuntu, BOM version 2.20.193.

**Comment by dpisklov** [comment]
So far only happened on Java 15, awaiting client's confirmation if it happens on Java 11.

**Comment by peter-lawrey** [comment]
Changed this assertion to a warning.
