### ISSUE TITLE
Java 16 (in-)compatibility

### ISSUE THREAD

**Issue by ginkel** [OpenHFT/Chronicle-Core#213]
Hello everyone,

now that Java 16 is out I tried using Chronicle Map running on a Java 16 JVM. Unfortunately, the static initialization of the Chronicle-Core `Jvm` class fails:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at net.openhft.chronicle.core.Jvm.get_setAccessible0_Method(Jvm.java:220)
	at net.openhft.chronicle.core.Jvm.<clinit>(Jvm.java:129)
	at de.tgbyte.reproducer.App.<clinit>(App.java:7)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.openhft.chronicle.core.Jvm.get_setAccessible0_Method(Jvm.java:217)
	... 2 more
Caused by: java.lang.IllegalAccessException: module java.base does not open java.lang.reflect to unnamed module @421faab1
	at java.base/java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:260)
	... 7 more
```

Full reproducer at: https://github.com/tgbyte/chronicle-core-jdk16

Thanks,
Thilo

**Comment by peter-lawrey** [comment]
There are a number of features used in `Jvm` for which there is no replacement.
Most likely we will have to use JNA in the future for Java 17+.

**Comment by peter-lawrey-admin** [comment]
In the meantime, you can try `--illegal-access=permit` for Java 16.
https://openjdk.java.net/jeps/396

**Comment by minborg** [comment]
Another useful JVM parameter is `--add-opens` which opens up modules for reflection.

**Comment by edudar** [comment]
These two worked for me to start an app with CM:
```
--add-opens java.base/java.lang.reflect=ALL-UNNAMED
--add-opens java.base/sun.nio.ch=ALL-UNNAMED
```
