### ISSUE TITLE
FileSystemWatcher is flaky

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Core#305]
Very often it would lead to
```
Exception in thread "watcher" java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /home/ilyak/w/c/Chronicle-Core/target/FileSystemWatcherTest-g5d8uj306y/dir2
	at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:88)
	at java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:104)
	at java.util.Iterator.forEachRemaining(Iterator.java:115)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at net.openhft.chronicle.core.watcher.FileSystemWatcher.bootstrapPath(FileSystemWatcher.java:173)
	at net.openhft.chronicle.core.watcher.FileSystemWatcher.bootstrap(FileSystemWatcher.java:163)
	at net.openhft.chronicle.core.watcher.FileSystemWatcher.run(FileSystemWatcher.java:114)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.NoSuchFileException: /home/ilyak/w/c/Chronicle-Core/target/FileSystemWatcherTest-g5d8uj306y/dir2
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:225)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
	at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:95)
	... 13 more

org.junit.ComparisonFailure: 
```
walk() [is not safe to use](https://bugs.openjdk.java.net/browse/JDK-8039910), it seems the only safe alternative is to move over to walkFileTree()

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.22ea20](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.22ea20), [BOM-2.22ea73](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea73)
