### ISSUE TITLE
GetSpecificationVersion can sometime return null and throw an NPE, which was not being caught

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Core#497]
When using vaNPE with the following version:

![image](https://user-images.githubusercontent.com/6506056/228583388-20fc388e-5d42-4260-a649-3f9e0fa9680a.png)

Stacktrace:
Exception in thread "main" java.lang.ExceptionInInitializerError
        at net.openhft.chronicle.core.UnsafeMemory.<clinit>(UnsafeMemory.java:73)
        at com.**.<…>
Caused by: java.lang.NullPointerException
        at net.openhft.chronicle.core.Bootstrap.getMajorVersion0(Bootstrap.java:112)
        at net.openhft.chronicle.core.Bootstrap.<clinit>(Bootstrap.java:69)
        ... 21 more

**Comment by dpisklov** [comment]
It's actually not fixed unfortunately - the fix has an issue in it. Because `Bootstrap#getMajorVersion0()` is called from Jvm class initializer, accessing Jvm.warn() throws NPE as well - there either must be no logging or logging should use System.err.println
