### ISSUE TITLE
Spurious bad file descriptor when running load tests on c2 with -DfastJava8IO=true

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Core#51]
TODO: more investigation, this is a placeholder for now.

```
java.io.IOException: Bad file descriptor
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at net.openhft.chronicle.core.OS.read0(OS.java:489)
        at net.openhft.chronicle.core.tcp.FastJ8SocketChannel.read0(FastJ8SocketChannel.java:84)
        at net.openhft.chronicle.core.tcp.FastJ8SocketChannel.read(FastJ8SocketChannel.java:30)
        at net.openhft.chronicle.network.TcpEventHandler.action(TcpEventHandler.java:198)
        at net.openhft.chronicle.threads.VanillaEventLoop.runAllMediumHandler(VanillaEventLoop.java:334)
        at net.openhft.chronicle.threads.VanillaEventLoop.runMediumLoopOnly(VanillaEventLoop.java:266)
        at net.openhft.chronicle.threads.VanillaEventLoop.runLoop(VanillaEventLoop.java:240)
        at net.openhft.chronicle.threads.VanillaEventLoop.run(VanillaEventLoop.java:221)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by JerryShea** [comment]
Seems to work reliably on dev1

**Comment by RobAustin** [comment]
closing it as won't fix - please reopen if it if you wish to fix it.
